import Image from 'next/image'
import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { blogArticles } from '@/lib/blog'

export const metadata = { title: 'Insights & Resources', description: 'Practical thinking on web development, SEO, mobile apps and custom software from The Orbit 7.' }

export default function BlogPage() {
  return <main className="min-h-screen bg-background"><header className="border-b border-border"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 sm:px-8 lg:px-10"><Link href="/" className="font-serif text-2xl text-primary">The Orbit 7</Link><Link href="/" className="text-sm font-semibold text-primary">Back to home</Link></div></header><section className="mx-auto max-w-7xl px-5 pb-20 pt-24 sm:px-8 lg:px-10 lg:pb-28 lg:pt-32"><p className="eyebrow">The Orbit 7 journal</p><h1 className="mt-4 max-w-3xl font-serif text-6xl leading-[.98] tracking-[-0.05em] text-primary sm:text-8xl">Insights &amp; Resources</h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted-foreground">Practical notes on building useful digital products, improving visibility and making technology work harder for your business.</p><div className="mt-16 grid gap-8 md:grid-cols-2">{blogArticles.map((article) => <article key={article.slug} className="group"><Link href={`/blog/${article.slug}`}><div className="relative aspect-[1.5] overflow-hidden rounded-2xl bg-muted"><Image src={article.image} alt={article.imageAlt} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition-transform duration-500 group-hover:scale-[1.03]" /></div><div className="mt-5 flex items-center gap-3 text-xs font-semibold uppercase tracking-[0.14em] text-primary"><span>{article.category}</span><span className="h-1 w-1 rounded-full bg-primary/40" /><span className="text-muted-foreground">{article.readingTime}</span></div><h2 className="mt-3 max-w-xl font-serif text-3xl leading-tight tracking-[-0.025em] text-primary">{article.title}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">{article.excerpt}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary">Read Article <ArrowUpRight size={16} /></span></Link></article>)}</div></section></main>
}
