import Image from 'next/image'
import { ArrowUpRight, BarChart3, Blocks, Check, Code2, Gauge, Globe2, Megaphone, PenTool, Search, Smartphone, UsersRound } from 'lucide-react'
import { MobileNav } from '@/components/mobile-nav'
import { ProjectForm } from '@/components/project-form'
import { ClientsSlider } from '@/components/clients-slider'
import { blogArticles } from '@/lib/blog'

const services = [
  { icon: Code2, name: 'Web Development', description: 'Fast, accessible websites and web apps engineered around your customers and business goals.' },
  { icon: Search, name: 'SEO', description: 'Technical SEO and content foundations that make your business easier to find and easier to trust.' },
  { icon: Smartphone, name: 'Mobile App Development', description: 'Reliable iOS and Android experiences that keep your customers connected to your product.' },
  { icon: BarChart3, name: 'Google Ads', description: 'Search campaigns built around intent, audiences and conversion paths that matter.' },
  { icon: Megaphone, name: 'Digital Marketing', description: 'Practical digital campaigns that turn attention into qualified conversations and growth.' },
  { icon: Blocks, name: 'Custom Software', description: 'Purpose-built software that removes manual work and gives your team room to scale.' },
  { icon: UsersRound, name: 'ERP & CRM Solutions', description: 'Connected systems for clearer operations, better customer context and stronger decisions.' },
]
const solutions = ['Business Websites', 'E-commerce Platforms', 'SaaS Products', 'Mobile Applications', 'ERP Systems', 'CRM Systems', 'Internal Business Tools', 'Custom Web Applications']
const process = [['01', 'Discover', 'Understand the business, users and goals.'], ['02', 'Plan', 'Define the right technology, structure and roadmap.'], ['03', 'Build', 'Design and develop with quality and scalability in mind.'], ['04', 'Launch', 'Deploy, test and optimize the final product.'], ['05', 'Grow', 'Keep improving performance, visibility and capability.']]
const technologies = ['Next.js', 'React', 'TypeScript', 'Node.js', 'Laravel', 'PHP', 'PostgreSQL', 'MySQL', 'Shopify', 'WordPress', 'React Native']
const reasons = ['Clear communication', 'Business-first thinking', 'Modern technology', 'Scalable solutions', 'Performance-minded delivery', 'Long-term support', 'Clean engineering', 'User-focused design']

function Logo({ priority = false }: { priority?: boolean }) { return <Image src="https://theorbit7.com/logo.png" alt="The Orbit 7" width={144} height={42} priority={priority} className="h-9 w-auto object-contain" /> }

export default function Page() {
  return <main id="top" className="overflow-hidden">
    <header className="absolute inset-x-0 top-0 z-20"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10"><a href="#top" aria-label="The Orbit 7 home"><Logo priority /></a><nav aria-label="Primary navigation" className="hidden items-center gap-7 lg:flex">{['Services', 'Solutions', 'Work', 'About', 'Insights', 'Contact'].map((item) => <a key={item} href={`#${item.toLowerCase()}`} className="text-sm text-muted-foreground hover:text-primary">{item}</a>)}<a href="#contact" className="rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground hover:-translate-y-0.5">Start a Project</a></nav><MobileNav /></div></header>
    <section className="relative border-b border-border bg-secondary/50 pt-36 sm:pt-44"><div className="mx-auto grid max-w-7xl items-end gap-16 px-5 pb-20 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:px-10 lg:pb-28"><div className="max-w-3xl"><p className="mb-7 flex items-center gap-3 text-xs font-semibold uppercase tracking-[0.18em] text-primary"><span className="h-px w-8 bg-primary" />Software development &amp; digital services</p><h1 className="max-w-4xl text-pretty font-serif text-5xl leading-[1.02] tracking-[-0.045em] text-primary sm:text-7xl lg:text-[86px]">Build digital products that move your business forward.</h1><p className="mt-8 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">The Orbit 7 builds websites, mobile applications and custom software — then helps businesses grow through SEO, digital marketing and technology solutions.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#contact" className="inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3.5 text-sm font-semibold text-primary-foreground hover:-translate-y-0.5">Start a Project <ArrowUpRight size={17} /></a><a href="#services" className="inline-flex items-center gap-2 rounded-full border border-primary/20 px-6 py-3.5 text-sm font-semibold text-primary hover:bg-card">Explore Services <ArrowUpRight size={17} /></a></div></div><div aria-hidden="true" className="relative hidden min-h-[390px] lg:block"><div className="absolute right-0 top-4 h-72 w-72 rounded-full border border-primary/15" /><div className="absolute right-16 top-20 h-44 w-44 rounded-full border border-primary/20" /><div className="absolute bottom-5 right-20 grid size-28 place-items-center rounded-full bg-primary text-primary-foreground shadow-2xl"><Globe2 size={42} strokeWidth={1.25} /></div><div className="absolute right-4 top-0 rounded-2xl border border-border bg-card px-5 py-4 shadow-lg"><p className="text-xs text-muted-foreground">Built for the long term</p><p className="mt-1 font-serif text-xl text-primary">Clear. Useful. Scalable.</p></div><div className="absolute bottom-0 left-10 h-36 w-44 rounded-2xl border border-border bg-card p-5 shadow-lg"><Gauge className="text-primary" size={22} /><p className="mt-8 text-sm leading-5 text-muted-foreground">Thoughtful systems, measured by outcomes.</p></div></div></div><div className="mx-auto max-w-7xl px-5 pb-8 sm:px-8 lg:px-10"><span className="font-mono text-xs text-muted-foreground">01 / 10</span></div></section>
    <section className="mx-auto grid max-w-7xl gap-8 px-5 py-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-10 lg:py-32"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">What we do</p><div><h2 className="max-w-3xl text-pretty font-serif text-4xl leading-tight tracking-[-0.03em] text-primary sm:text-5xl">We design, build and grow digital products for businesses that want technology to work harder.</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">From a high-performing marketing site to the internal software your team relies on every day, we bring strategy, design and engineering together in one focused team.</p></div></section>
    <section id="services" className="border-y border-border bg-muted/45"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Services</p><h2 className="section-title mt-4">The right work for<br className="hidden sm:block" /> the next stage.</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">A practical mix of product development and growth services, shaped around what your business needs now.</p></div><div className="mt-16 grid gap-px overflow-hidden rounded-2xl border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{services.map(({ icon: Icon, name, description }, index) => <article key={name} className={`group bg-background p-7 hover:bg-card ${index === 0 ? 'lg:col-span-2' : ''}`}><Icon size={24} strokeWidth={1.5} className="text-primary" /><h3 className="mt-12 font-serif text-2xl tracking-[-0.02em] text-primary">{name}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-muted-foreground">{description}</p><span className="mt-7 inline-flex items-center gap-1 text-sm font-semibold text-primary opacity-0 transition-opacity group-hover:opacity-100">Learn more <ArrowUpRight size={15} /></span></article>)}</div></div></section>
    <ClientsSlider />
    <section id="solutions" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Solutions</p><h2 className="section-title mt-4">Technology that fits the way you work.</h2></div><div className="grid grid-cols-1 gap-x-12 sm:grid-cols-2">{solutions.map((solution, index) => <div key={solution} className="flex items-center justify-between border-t border-border py-5"><span className="text-base text-primary">{solution}</span><span className="font-mono text-xs text-muted-foreground">0{index + 1}</span></div>)}</div></div></section>
    <section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary-foreground/60">How we work</p><h2 className="mt-4 font-serif text-4xl tracking-[-0.03em] sm:text-5xl">A clear path from first conversation to launch.</h2></div><div className="grid gap-0">{process.map(([number, title, description]) => <div key={number} className="grid gap-5 border-t border-primary-foreground/20 py-6 sm:grid-cols-[70px_180px_1fr] sm:items-center"><span className="font-mono text-sm text-primary-foreground/50">{number}</span><h3 className="font-serif text-2xl">{title}</h3><p className="text-sm leading-6 text-primary-foreground/65">{description}</p></div>)}</div></div></div></section>
    <section id="work" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Selected work</p><h2 className="section-title mt-4">Work in progress,<br className="hidden sm:block" /> thoughtfully presented.</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">A space for projects that show how we think. Real case studies will be added here as they launch.</p></div><div className="mt-16 grid gap-6 lg:grid-cols-2"><article className="group overflow-hidden rounded-2xl border border-border bg-muted/40"><div className="flex aspect-[1.45] items-end bg-secondary p-8"><div className="w-full rounded-xl border border-primary/15 bg-card p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">Product thinking</p><h3 className="mt-3 font-serif text-3xl text-primary">A digital product, built around the user.</h3><div className="mt-8 flex gap-2"><span className="rounded-full bg-muted px-3 py-1 text-xs text-muted-foreground">Strategy</span><span className="rounded-full bg-muted px-3 py-1 text-xs text-muted-foreground">Development</span></div></div></div><div className="flex items-center justify-between p-6"><div><h3 className="font-semibold text-primary">Project name to come</h3><p className="mt-1 text-sm text-muted-foreground">Industry · Short project description</p></div><span className="grid size-10 place-items-center rounded-full border border-border text-primary group-hover:bg-primary group-hover:text-primary-foreground"><ArrowUpRight size={17} /></span></div></article><article className="group overflow-hidden rounded-2xl border border-border bg-muted/40"><div className="relative aspect-[1.45]"><Image src="https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=1200&q=85" alt="Clean digital product interface displayed on a desktop screen" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /></div><div className="flex items-center justify-between p-6"><div><h3 className="font-semibold text-primary">A sharper digital experience</h3><p className="mt-1 text-sm text-muted-foreground">Design · Development · Coming soon</p></div><PenTool size={21} strokeWidth={1.3} className="text-primary" /></div></article></div></section>
    <section aria-labelledby="awards-title" className="border-y border-border bg-secondary/60"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="eyebrow">Recognition</p><h2 id="awards-title" className="mt-4 max-w-xl font-serif text-4xl leading-tight tracking-[-0.03em] text-primary sm:text-5xl">Work that earns its place.</h2></div><p className="max-w-md text-base leading-7 text-muted-foreground">We bring an award-worthy level of care to every build: thoughtful strategy, clear systems and digital experiences made to last.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-3"><div className="bg-background p-7"><p className="font-mono text-xs uppercase tracking-[0.15em] text-muted-foreground">Awards</p><p className="mt-5 font-serif text-2xl text-primary">Recognition coming soon</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Digital craft and experience</p></div><div className="bg-background p-7"><p className="font-mono text-xs uppercase tracking-[0.15em] text-muted-foreground">Industry</p><p className="mt-5 font-serif text-2xl text-primary">Recognition-ready work</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Interface and interaction</p></div><div className="bg-background p-7"><p className="font-mono text-xs uppercase tracking-[0.15em] text-muted-foreground">Recognition</p><p className="mt-5 font-serif text-2xl text-primary">Built to be remembered</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Technology and delivery</p></div></div></div></section>
    <section id="about" className="border-y border-border bg-muted/45"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:px-10 lg:py-32"><div><p className="eyebrow">Why The Orbit 7</p><h2 className="section-title mt-4">Good technology should make the business clearer.</h2></div><div><p className="max-w-2xl text-xl leading-8 text-primary">We keep strategy close to the work, communicate in plain language and build systems that remain useful after launch.</p><div className="mt-12 grid gap-x-8 gap-y-5 sm:grid-cols-2">{reasons.map((reason) => <div key={reason} className="flex items-center gap-3 border-t border-border pt-4 text-sm text-muted-foreground"><Check size={16} className="text-primary" />{reason}</div>)}</div></div></div></section>
    <section id="technology" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-28"><div className="flex flex-col gap-10 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Technology</p><h2 className="mt-4 font-serif text-3xl tracking-[-0.03em] text-primary sm:text-4xl">Tools that help us build well.</h2></div><div className="flex max-w-2xl flex-wrap gap-2">{technologies.map((tech) => <span key={tech} className="rounded-full border border-border px-4 py-2 text-sm text-muted-foreground">{tech}</span>)}</div></div></section>
    <section id="insights" className="border-y border-border bg-muted/45"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Journal</p><h2 className="section-title mt-4">Insights &amp; Resources</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">Practical thinking on digital products, visibility and the systems behind growing businesses.</p></div><div className="mt-14 grid gap-8 md:grid-cols-2 lg:grid-cols-4">{blogArticles.map((article) => <article key={article.slug} className="group"><a href={`/blog/${article.slug}`}><div className="relative aspect-[1.35] overflow-hidden rounded-2xl bg-muted"><Image src={article.image} alt={article.imageAlt} fill sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 25vw" className="object-cover transition-transform duration-500 group-hover:scale-[1.03]" /></div><p className="mt-5 text-xs font-semibold uppercase tracking-[0.14em] text-primary">{article.category}</p><h3 className="mt-3 font-serif text-2xl leading-tight tracking-[-0.02em] text-primary">{article.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{article.excerpt}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary">Read Article <ArrowUpRight size={15} /></span></a></article>)}</div></div></section>
    <section id="contact" className="bg-secondary"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><div><p className="eyebrow">Start a conversation</p><h2 className="mt-4 font-serif text-5xl leading-[1.05] tracking-[-0.04em] text-primary sm:text-6xl">Have a project in mind?</h2><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">Tell us what you&apos;re building. Share the useful details and we&apos;ll help you figure out the right way forward.</p><p className="mt-8 text-sm leading-6 text-muted-foreground">Prefer email? <a href="mailto:hello@theorbit7.com" className="font-semibold text-primary underline underline-offset-4">hello@theorbit7.com</a></p></div><ProjectForm /></div></div></section>
    <footer className="bg-background"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:px-10"><div className="grid gap-12 md:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><Logo /><p className="mt-5 max-w-xs text-sm leading-6 text-muted-foreground">Software development and digital services for businesses ready to move forward.</p></div><div><p className="footer-heading">Services</p>{services.slice(0, 4).map(({ name }) => <a key={name} href="#services" className="footer-link">{name}</a>)}</div><div><p className="footer-heading">Company</p>{['About', 'Work', 'Solutions', 'Insights', 'Contact'].map((item) => <a key={item} href={`#${item.toLowerCase()}`} className="footer-link">{item}</a>)}</div><div><p className="footer-heading">Contact</p><a href="mailto:hello@theorbit7.com" className="footer-link">hello@theorbit7.com</a><a href="#contact" className="footer-link">Start a project</a></div></div><div className="mt-14 flex flex-col justify-between gap-4 border-t border-border pt-6 text-xs text-muted-foreground sm:flex-row"><p>© 2026 The Orbit 7. All rights reserved.</p><div className="flex gap-5"><a href="#top">Privacy Policy</a><a href="#top">Terms &amp; Conditions</a></div></div></div></footer>
  </main>
}
